import { pgTable, uuid, varchar, text, integer, boolean, timestamp, jsonb, uniqueIndex, index, pgEnum } from "drizzle-orm/pg-core";

export const roleEnum = pgEnum("role", ["customer", "admin"]);
export const orderStatusEnum = pgEnum("order_status", ["pending", "confirmed", "processing", "shipped", "delivered", "completed", "cancelled", "refunded"]);
export const paymentStatusEnum = pgEnum("payment_status", ["pending", "processing", "success", "failed", "cancelled", "expired", "refunded", "partially_refunded"]);
export const shipmentStatusEnum = pgEnum("shipment_status", ["pending", "preparing", "shipped", "delivered", "cancelled"]);
export const invoiceStatusEnum = pgEnum("invoice_status", ["draft", "issued", "paid", "cancelled"]);
export const refundStatusEnum = pgEnum("refund_status", ["pending", "processed", "failed", "cancelled"]);
export const notificationStatusEnum = pgEnum("notification_status", ["pending", "sent", "failed"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull(), email: varchar("email", { length: 190 }).notNull().unique(), phone: varchar("phone", { length: 30 }), passwordHash: text("password_hash").notNull(), role: roleEnum("role").default("customer").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), lastLoginAt: timestamp("last_login_at", { withTimezone: true })
}, (t) => [index("users_role_idx").on(t.role)]);

export const passwordResetTokens = pgTable("password_reset_tokens", {
  id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull()
}, (t) => [index("password_reset_user_idx").on(t.userId), index("password_reset_expiry_idx").on(t.expiresAt)]);

export const rateLimits = pgTable("rate_limits", {
  key: varchar("key", { length: 220 }).primaryKey(), count: integer("count").notNull(), resetAt: timestamp("reset_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull()
}, (t) => [index("rate_limits_reset_idx").on(t.resetAt)]);

export const addresses = pgTable("addresses", {
  id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), label: varchar("label", { length: 80 }), recipientName: varchar("recipient_name", { length: 120 }).notNull(), phone: varchar("phone", { length: 30 }).notNull(), addressLine: text("address_line").notNull(), city: varchar("city", { length: 100 }).notNull(), region: varchar("region", { length: 100 }), country: varchar("country", { length: 2 }).default("CM").notNull(), postalCode: varchar("postal_code", { length: 20 }), isDefault: boolean("is_default").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull()
}, (t) => [index("addresses_user_idx").on(t.userId)]);

export const categories = pgTable("categories", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 100 }).notNull().unique(), slug: varchar("slug", { length: 120 }).notNull().unique(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });

export const products = pgTable("products", {
  id: uuid("id").defaultRandom().primaryKey(), categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }), sku: varchar("sku", { length: 80 }), name: varchar("name", { length: 160 }).notNull(), slug: varchar("slug", { length: 180 }).notNull().unique(), description: text("description"), priceXaf: integer("price_xaf").notNull(), promoPriceXaf: integer("promo_price_xaf"), imageUrl: text("image_url"), stock: integer("stock").default(1).notNull(), lowStockThreshold: integer("low_stock_threshold").default(2).notNull(), isCustom: boolean("is_custom").default(true).notNull(), published: boolean("published").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull()
}, (t) => [uniqueIndex("products_sku_unique").on(t.sku), index("products_published_created_idx").on(t.published, t.createdAt), index("products_category_idx").on(t.categoryId)]);

export const productImages = pgTable("product_images", { id: uuid("id").defaultRandom().primaryKey(), productId: uuid("product_id").references(() => products.id, { onDelete: "cascade" }).notNull(), imageUrl: text("image_url").notNull(), altText: varchar("alt_text", { length: 180 }), sortOrder: integer("sort_order").default(0).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("product_images_product_idx").on(t.productId)]);
export const gallery = pgTable("gallery", { id: uuid("id").defaultRandom().primaryKey(), title: varchar("title", { length: 160 }).notNull(), category: varchar("category", { length: 100 }), imageUrl: text("image_url").notNull(), description: text("description"), published: boolean("published").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("gallery_published_idx").on(t.published)]);
export const services = pgTable("services", { id: uuid("id").defaultRandom().primaryKey(), title: varchar("title", { length: 160 }).notNull(), slug: varchar("slug", { length: 180 }).notNull().unique(), description: text("description"), icon: varchar("icon", { length: 40 }), published: boolean("published").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull() });

export const carts = pgTable("carts", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull().unique(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const cartItems = pgTable("cart_items", { id: uuid("id").defaultRandom().primaryKey(), cartId: uuid("cart_id").references(() => carts.id, { onDelete: "cascade" }).notNull(), productId: uuid("product_id").references(() => products.id, { onDelete: "restrict" }).notNull(), quantity: integer("quantity").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("cart_product_unique").on(t.cartId, t.productId), index("cart_items_cart_idx").on(t.cartId)]);

export const orders = pgTable("orders", {
  id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), status: orderStatusEnum("status").default("pending").notNull(), subtotalXaf: integer("subtotal_xaf").default(0).notNull(), deliveryFeeXaf: integer("delivery_fee_xaf").default(0).notNull(), discountXaf: integer("discount_xaf").default(0).notNull(), taxXaf: integer("tax_xaf").default(0).notNull(), currency: varchar("currency", { length: 3 }).default("XAF").notNull(), idempotencyKey: varchar("idempotency_key", { length: 120 }), totalXaf: integer("total_xaf").notNull(), customerNote: text("customer_note"), shippingRecipientName: varchar("shipping_recipient_name", { length: 120 }), shippingPhone: varchar("shipping_phone", { length: 30 }), shippingAddressLine: text("shipping_address_line"), shippingCity: varchar("shipping_city", { length: 100 }), shippingRegion: varchar("shipping_region", { length: 100 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), stockReleasedAt: timestamp("stock_released_at", { withTimezone: true })
}, (t) => [uniqueIndex("orders_idempotency_unique").on(t.idempotencyKey), index("orders_user_created_idx").on(t.userId, t.createdAt), index("orders_status_idx").on(t.status)]);

export const orderItems = pgTable("order_items", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), productId: uuid("product_id").references(() => products.id, { onDelete: "restrict" }).notNull(), productNameSnapshot: varchar("product_name_snapshot", { length: 160 }).notNull(), skuSnapshot: varchar("sku_snapshot", { length: 80 }), quantity: integer("quantity").notNull(), unitPriceXaf: integer("unit_price_xaf").notNull() }, (t) => [index("order_items_order_idx").on(t.orderId), index("order_items_product_idx").on(t.productId)]);

export const payments = pgTable("payments", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), provider: varchar("provider", { length: 40 }).notNull(), transactionId: varchar("transaction_id", { length: 120 }).notNull().unique(), amountXaf: integer("amount_xaf").notNull(), currency: varchar("currency", { length: 3 }).notNull(), status: paymentStatusEnum("status").default("pending").notNull(), paymentUrl: text("payment_url"), providerReference: varchar("provider_reference", { length: 180 }), providerResponse: jsonb("provider_response"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), paidAt: timestamp("paid_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }) }, (t) => [index("payments_order_idx").on(t.orderId), index("payments_status_idx").on(t.status), index("payments_expiry_idx").on(t.expiresAt)]);
export const paymentEvents = pgTable("payment_events", { id: uuid("id").defaultRandom().primaryKey(), paymentId: uuid("payment_id").references(() => payments.id, { onDelete: "cascade" }), provider: varchar("provider", { length: 40 }).notNull(), eventId: varchar("event_id", { length: 180 }).notNull().unique(), eventType: varchar("event_type", { length: 80 }).notNull(), payload: jsonb("payload").notNull(), receivedAt: timestamp("received_at", { withTimezone: true }).defaultNow().notNull(), processedAt: timestamp("processed_at", { withTimezone: true }), status: varchar("status", { length: 30 }).default("received").notNull() }, (t) => [index("payment_events_payment_idx").on(t.paymentId)]);
export const refunds = pgTable("refunds", { id: uuid("id").defaultRandom().primaryKey(), paymentId: uuid("payment_id").references(() => payments.id).notNull(), amountXaf: integer("amount_xaf").notNull(), reason: text("reason"), status: refundStatusEnum("status").default("pending").notNull(), providerReference: varchar("provider_reference", { length: 180 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), processedAt: timestamp("processed_at", { withTimezone: true }) }, (t) => [index("refunds_payment_idx").on(t.paymentId)]);

export const shipments = pgTable("shipments", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull().unique(), status: shipmentStatusEnum("status").default("pending").notNull(), carrier: varchar("carrier", { length: 120 }), trackingNumber: varchar("tracking_number", { length: 120 }), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), shippedAt: timestamp("shipped_at", { withTimezone: true }), deliveredAt: timestamp("delivered_at", { withTimezone: true }) });
export const invoices = pgTable("invoices", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull().unique(), invoiceNumber: varchar("invoice_number", { length: 60 }).notNull().unique(), status: invoiceStatusEnum("status").default("draft").notNull(), subtotalXaf: integer("subtotal_xaf").notNull(), deliveryFeeXaf: integer("delivery_fee_xaf").notNull(), discountXaf: integer("discount_xaf").notNull(), taxXaf: integer("tax_xaf").notNull(), totalXaf: integer("total_xaf").notNull(), currency: varchar("currency", { length: 3 }).default("XAF").notNull(), issuedAt: timestamp("issued_at", { withTimezone: true }), paidAt: timestamp("paid_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }), type: varchar("type", { length: 60 }).notNull(), channel: varchar("channel", { length: 30 }).default("in_app").notNull(), status: notificationStatusEnum("status").default("pending").notNull(), title: varchar("title", { length: 180 }).notNull(), message: text("message").notNull(), sentAt: timestamp("sent_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("notifications_user_idx").on(t.userId, t.createdAt)]);
export const contactRequests = pgTable("contact_requests", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull(), phone: varchar("phone", { length: 30 }).notNull(), email: varchar("email", { length: 190 }), subject: varchar("subject", { length: 180 }), message: text("message").notNull(), status: varchar("status", { length: 30 }).default("new").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), handledAt: timestamp("handled_at", { withTimezone: true }) }, (t) => [index("contact_requests_status_idx").on(t.status)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), action: varchar("action", { length: 100 }).notNull(), entityType: varchar("entity_type", { length: 60 }).notNull(), entityId: varchar("entity_id", { length: 120 }), metadata: jsonb("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("audit_logs_created_idx").on(t.createdAt), index("audit_logs_actor_idx").on(t.actorUserId)]);
