import Link from "next/link";
import { eq, and } from "drizzle-orm";
import { db } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";
import { orders, payments } from "@/lib/db/schema";
import { formatXaf, orderReference } from "@/lib/utils";
import RefreshPaymentStatus from "@/components/RefreshPaymentStatus";
// Détails techniques (ne pas afficher) : le retour du guichet n'est jamais une preuve de
// paiement ; la commande est validée uniquement après confirmation côté serveur (vérification
// serveur-à-serveur + webhook). Statut brut du paiement réservé aux logs.
export default async function RetourPaiement({searchParams}:{searchParams:Promise<{order?:string}>}){const u=await getCurrentUser();const q=await searchParams;let order:any=null,payment:any=null;if(u&&q.order){[order]=await db.select().from(orders).where(and(eq(orders.id,q.order),eq(orders.userId,u.id))).limit(1);if(order)[payment]=await db.select().from(payments).where(eq(payments.orderId,order.id)).limit(1)}const nextLogin=q.order?`/connexion?next=${encodeURIComponent(`/paiement/retour?order=${q.order}`)}`:"/connexion";return <main className="section"><div className="container" style={{maxWidth:760}}><div className="card"><span className="eyebrow">Paiement</span><h1>{payment?.status==='success'?'Paiement confirmé':payment?.status==='failed'||payment?.status==='cancelled'||payment?.status==='expired'?'Paiement non abouti':'Paiement en vérification'}</h1>{order?<><p>Commande <strong>{orderReference(order.id)}</strong></p><p>Montant : <strong>{formatXaf(order.totalXaf)}</strong></p><p>{payment?.status==='success'?'Votre commande est confirmée.':payment?.status==='failed'||payment?.status==='cancelled'||payment?.status==='expired'?'Le paiement n\'a pas abouti. Réessayez ou contactez-nous sur WhatsApp.':'Vérification en cours. Bientôt disponible.'}</p><RefreshPaymentStatus orderId={order.id} initialStatus={payment?.status||"pending"}/></>:<p>Connectez-vous pour consulter votre commande.</p>}<div className="actions">{!u&&q.order?<Link className="btn btn-gold" href={nextLogin}>Se connecter</Link>:<Link className="btn btn-gold" href="/compte">Voir mon compte</Link>}<Link className="btn" href="/boutique">Retour à la boutique</Link></div></div></div></main>}
