"use client";
import {useEffect,useState} from 'react';

type Product={id:string;name:string;slug:string;priceXaf:number;promoPriceXaf:number|null;stock:number;published:boolean;imageUrl:string|null;description:string|null;sku:string|null;categoryId:string|null};
const tabs=[['products','Produits'],['orders','Commandes'],['categories','Catégories'],['gallery','Galerie'],['services','Services'],['customers','Clients'],['payments','Paiements'],['refunds','Remboursements'],['contact','Messages'],['logs','Journal']];
const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
export default function AdminConsole({initialProducts}:{initialProducts:Product[]}){
 const [products,setProducts]=useState(initialProducts),[tab,setTab]=useState('products'),[orders,setOrders]=useState<any[]>([]),[data,setData]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const [f,setF]=useState({name:'',slug:'',description:'',priceXaf:'',promoPriceXaf:'',imageUrl:'',stock:'1',sku:'',categoryId:''});
 const load=async()=>{const map:any={orders:'/api/admin/orders',categories:'/api/admin/categories',gallery:'/api/admin/gallery',services:'/api/admin/services',customers:'/api/admin/customers',payments:'/api/admin/payments',refunds:'/api/admin/refunds',contact:'/api/admin/contact',logs:'/api/admin/audit-logs'};if(!map[tab])return;const r=await fetch(map[tab],{cache:'no-store'});if(r.ok)setData(await r.json())};
 useEffect(()=>{fetch('/api/admin/categories',{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(setCategories)},[]);useEffect(()=>{if(tab==='orders')load();else if(tab!=='products')load()},[tab]);
 async function addProduct(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');const body={...f,priceXaf:Number(f.priceXaf),promoPriceXaf:f.promoPriceXaf?Number(f.promoPriceXaf):null,imageUrl:f.imageUrl||null,stock:Number(f.stock),sku:f.sku||null,categoryId:f.categoryId||null};const r=await fetch('/api/products',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Erreur');return}setProducts([j,...products]);setMsg('Article ajouté.');setF({name:'',slug:'',description:'',priceXaf:'',promoPriceXaf:'',imageUrl:'',stock:'1',sku:'',categoryId:''})}
 async function archive(id:string){if(!confirm('Archiver cet article ?'))return;const r=await fetch('/api/products',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});if(r.ok)setProducts(products.map(p=>p.id===id?{...p,published:false}:p))}
 async function updateOrder(id:string,status:string){const r=await fetch('/api/admin/orders',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});if(r.ok)load();else alert((await r.json()).error||'Impossible de modifier la commande')}
 async function addResource(endpoint:string,body:any){const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){alert(j.error||'Erreur');return}load()}
 return <div><div className="admin-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='products'&&<><form className="card form" onSubmit={addProduct} style={{margin:'25px 0'}}><h3>Ajouter un article</h3><div className="form-grid"><input placeholder="Nom" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input placeholder="Slug" value={f.slug} onChange={e=>setF({...f,slug:e.target.value})} required/><input placeholder="SKU / référence" value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/><input placeholder="Prix FCFA (multiple de 5)" type="number" min="0" step="5" value={f.priceXaf} onChange={e=>setF({...f,priceXaf:e.target.value})} required/><input placeholder="Prix promo" type="number" min="0" step="5" value={f.promoPriceXaf} onChange={e=>setF({...f,promoPriceXaf:e.target.value})}/><input placeholder="Stock" type="number" min="0" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})}/><select value={f.categoryId} onChange={e=>setF({...f,categoryId:e.target.value})}><option value="">Sans catégorie</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><input placeholder="URL image" value={f.imageUrl} onChange={e=>setF({...f,imageUrl:e.target.value})}/><textarea placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/>{msg&&<small>{msg}</small>}<button className="btn btn-gold" disabled={busy}>{busy?'Enregistrement...':'Publier l’article'}</button></form><div className="shop-grid">{products.map(x=><article className="product" key={x.id}>{x.imageUrl&&<img src={x.imageUrl} alt={x.name}/>}<div className="product-body"><h3>{x.name}</h3><p>SKU : {x.sku||'—'}<br/>Stock : {x.stock}<br/>{x.published?'Publié':'Archivé'}</p><div className="price">{money(x.promoPriceXaf??x.priceXaf)}</div>{x.published&&<button className="btn" onClick={()=>archive(x.id)}>Archiver</button>}</div></article>)}</div></>}
 {tab==='orders'&&<div className="order-list">{data.map(x=><article className="card" key={x.order.id}><div><strong>{x.order.id.slice(0,8).toUpperCase()}</strong><p>{x.userName} · {x.userEmail}<br/>Paiement : {x.paymentStatus||'—'} · Livraison : {x.shipmentStatus||'—'}</p></div><div><strong>{money(x.order.totalXaf)}</strong><select value={x.order.status} onChange={e=>updateOrder(x.order.id,e.target.value)}><option value="pending">pending</option><option value="confirmed">confirmed</option><option value="processing">processing</option><option value="shipped">shipped</option><option value="delivered">delivered</option><option value="completed">completed</option><option value="cancelled">cancelled</option><option value="refunded">refunded</option></select></div></article>)}</div>}
 {tab==='categories'&&<ResourceForm title="Catégories" fields={[['name','Nom'],['slug','Slug']]} onSubmit={v=>addResource('/api/admin/categories',v)} rows={data} labels={['name','slug']}/>} 
 {tab==='gallery'&&<ResourceForm title="Galerie" fields={[['title','Titre'],['category','Catégorie'],['imageUrl','URL image'],['description','Description']]} onSubmit={v=>addResource('/api/admin/gallery',{...v,published:true})} rows={data} labels={['title','category','imageUrl']}/>} 
 {tab==='services'&&<ResourceForm title="Services" fields={[['title','Titre'],['slug','Slug'],['description','Description'],['icon','Icône']]} onSubmit={v=>addResource('/api/admin/services',{...v,published:true,sortOrder:0})} rows={data} labels={['title','slug','description']}/>} 
 {tab==='customers'&&<List title="Clients" rows={data} render={x=><div><strong>{x.name}</strong><p>{x.email} · {x.phone||'sans téléphone'} · {x.role}</p></div>}/>} 
 {tab==='payments'&&<List title="Paiements" rows={data} render={x=><div><strong>{x.payment.transactionId}</strong><p>{x.userName} · {money(x.payment.amountXaf)} · {x.payment.status}</p></div>}/>} 
 {tab==='refunds'&&<RefundList rows={data} reload={load}/>} 
 {tab==='logs'&&<List title="Journal d’audit" rows={data} render={x=><div><strong>{x.action}</strong><p>{x.entityType} · {x.entityId||'—'}<br/>{new Date(x.createdAt).toLocaleString('fr-FR')}</p></div>}/>}
 {tab==='contact'&&<List title="Messages" rows={data} render={x=><div><strong>{x.subject||'Demande de contact'}</strong><p>{x.name} · {x.phone} · {x.status}<br/>{x.message}</p></div>}/>} 
 </div>
}
function List({title,rows,render}:{title:string;rows:any[];render:(x:any)=>React.ReactNode}){return <section><h2>{title}</h2><div className="order-list">{rows.map((x,i)=><article className="card" key={x.id||x.payment?.id||i}>{render(x)}</article>)}{!rows.length&&<div className="card">Aucun élément.</div>}</div></section>}
function ResourceForm({title,fields,onSubmit,rows,labels}:{title:string;fields:string[][];onSubmit:(v:any)=>void;rows:any[];labels:string[]}){const [v,setV]=useState<Record<string,string>>({});return <section><h2>{title}</h2><form className="card form" onSubmit={e=>{e.preventDefault();onSubmit(v);setV({})}}><div className="form-grid">{fields.map(([k,l])=><input key={k} placeholder={l} value={v[k]||''} onChange={e=>setV({...v,[k]:e.target.value})} required={k!=='description'&&k!=='icon'}/>)}</div><button className="btn btn-gold">Ajouter</button></form><div className="order-list" style={{marginTop:20}}>{rows.map(x=><article className="card" key={x.id}>{labels.map(k=><p key={k}><strong>{k}:</strong> {x[k]||'—'}</p>)}</article>)}</div></section>}
function RefundList({rows,reload}:{rows:any[];reload:()=>void}){return <section><h2>Remboursements</h2><div className="order-list">{rows.map(x=><article className="card" key={x.refund.id}><p><strong>{money(x.refund.amountXaf)}</strong> · {x.refund.status}<br/>Transaction : {x.payment.transactionId}</p>{x.refund.status==='pending'&&<div className="actions"><button className="btn" onClick={async()=>{await fetch('/api/admin/refunds',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:x.refund.id,status:'processed',providerReference:prompt('Référence prestataire (optionnel)')||undefined})});reload()}}>Marquer traité</button><button className="btn" onClick={async()=>{await fetch('/api/admin/refunds',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:x.refund.id,status:'failed'})});reload()}}>Échec</button></div>}</article>)}</div></section>}
